sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- iojs-v2
- iojs-v1
- '0.12'
- '0.10'
before_install:
- npm i -g npm@^2.0.0
install:
- npm install --no-optional
before_script:
- npm prune
- curl -Lo travis_after_all.py https://git.io/vLSON
after_script:
- npm run coverage:upload
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
- if [[ $BUILD_LEADER = YES ]]; then npm run coverage:upload; fi
- npm run semantic-release
