before_script:
  - npm install -g grunt-cli
language: node_js
node_js:
  - "0.10"
  - "0.8"
notifications:
  irc:
    channels:
      - "chat.freenode.net#hoodie"
    use_notice: true
    skip_join: true
